export enum controllerAction {
    HANDLE_MENU_TOGGLE = 'HANDLE_MENU_TOGGLE',
    HANDLE_MENU_OPEN = 'HANDLE_MENU_OPEN',
    HANDLE_MENU_CLOSE = 'HANDLE_MENU_CLOSE',
    HANDLE_MENU_SET = 'HANDLE_MENU_SET',
}
